version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/todo.txt:/app/todo.txt
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development 
    networks:
      - todo_network

  frontend:
    build: ./frontend
    ports:
      - "80:80" 
    depends_on:
      - backend 
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge