version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend # ✅ pastikan ini sama persis dengan nama servicenya

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
